### ISSUE TITLE
Historical tab

### ISSUE THREAD

**Issue by prquinlan** [biobankinguk/biobankinguk#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I go to the historical tab as the admin user, it does not show recent decisions. 

https://directory.biobankinguk.org/ADAC/Historical

### Expected Behavior

It would list the biobanks we have said yes/no to

### Steps To Reproduce

Register a new biobank
Accept/reject the request
It wont appear here: https://directory.biobankinguk.org/ADAC/Historical

### Environment

```markdown
- OS:
- Other environment details:
```

**Comment by AndyRae** [comment]
I assume this refers to the existing production application given the links within it.

It _might_ be fixed in V4 #555 

`Fixes Historical biobank requests, previous accepted biobank requests were completely filtered out (this is a bug from the live app)`

**Comment by prquinlan** [comment]
Still seems to be a problem. I added a new biobank, and accepted the invitation, but nothing appears in the list

**Comment by AndyRae** [comment]
Interesting - I have accepted and declined an invitation on dev now, and they do appear in the list.

However... the list is not sorted by date traditionally, so the latest requests will not appear at the top. Could you check whether your accepted/declined requests are in the list at all? I can see `Bob Smith` on `07/23/2024` for example.

@blargly 
The bug here to fix - the sorting in this list is done by reverse date in mm/dd format, as a string object... so requests in late December will be the latest.

**Comment by prquinlan** [comment]
Ah, right, so yes I did do the clicking to re-order, had not twigged it was formatted m/d/y

**Comment by blargly** [comment]
Lower priority in that case?

**Comment by AndyRae** [comment]
Yes - it needs fixing, but as the content is there this can be done post-live.

**Comment by AndyRae** [comment]
This is fine locally - as in, dates are `dd/mm/yyyy` and the page works as expected, so this looks to be localisation in app service.
Maybe fixed with: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization ?
